USE DISA_TRAVELS;

CREATE TABLE `PAYMENT INFO` (
	id						INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	card1Number				VARCHAR(16) NOT NULL,
	cvv						VARCHAR(3) NOT NULL,
	expirationDate			DATE NOT NULL,
	cardType				VARCHAR(20) NOT NULL,
	branchCode				VARCHAR(10) NOT NULL,
	bank					VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `GUEST` (
	id				INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	title			VARCHAR(5) NOT NULL,
	firstName		VARCHAR(30) NOT NULL,
	lastName		VARCHAR(30) NOT NULL
	username		VARCHAR(300) UNIQUE NOT NULL,
	password		VARCHAR(32) UNIQUE NOT NULL,
	strAddress		VARCHAR(30) NOT NULL,
	suburb			VARCHAR(30),
	town			VARCHAR(30) NOT NULL,
	birthday		DATE NOT NULL,
	mobileNumber	VARCHAR(10) NOT NULL,
	gender			INT UNSIGNED NOT NULL,
	description		VARCHAR(300),
	profilePicture	BLOB,
	payInfoID		INT UNSIGNED,
	CONSTRAINT FK_PAYINFO_ID_GUEST FOREIGN KEY (payInfoID) REFERENCES `PAYMENT INFO`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `HOST` (
	id				INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	title			VARCHAR(5) NOT NULL,
	firstName		VARCHAR(30) NOT NULL,
	lastName		VARCHAR(30) NOT NULL,
	username		VARCHAR(300) NOT NULL,
	password		VARCHAR(32) UNIQUE NOT NULL,
	strAddress		VARCHAR(30) NOT NULL,
	suburb			VARCHAR(30),
	town			VARCHAR(30) NOT NULL,
	birthday		DATE NOT NULL,
	mobileNumber	VARCHAR(10) NOT NULL,
	gender			INT UNSIGNED NOT NULL,
	description		VARCHAR(300),
	profilePic		BLOB
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ADMINISTRATOR` (
	id				INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	title			VARCHAR(5) NOT NULL,
	firstName		VARCHAR(30) NOT NULL,
	lastName		VARCHAR(30) NOT NULL,
	username		VARCHAR(300) UNIQUE NOT NULL,
	password		VARCHAR(32) UNIQUE NOT NULL,
	mobileNumber	VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `LISTING` (
	id						INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	accommodationType		VARCHAR(10) NOT NULL,
	name					VARCHAR(50) NOT NULL,
	hostID					INT UNSIGNED,
	strAddress				VARCHAR(30) NOT NULL,
	suburb					VARCHAR(30),
	town					VARCHAR(30) NOT NULL,
	addressCoordinates		VARCHAR(50) NOT NULL,
	availableRooms			INT UNSIGNED NOT NULL,
	accommodationCapacity	INT UNSIGNED NOT NULL,
	tarrif					DECIMAL(6, 2) NOT NULL,
	minBookingDays			INT UNSIGNED NOT NULL,
	tags					VARCHAR(300),
	description				VARCHAR(300),
	image1					BLOB,
	image2					BLOB,
	image3					BLOB,
	image4					BLOB,
	image5					BLOB,
	CONSTRAINT FK_HOST_ID_LISTING FOREIGN KEY (hostID) REFERENCES `HOST`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `LISTING REVIEW` (
	id						INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	listingID				INT UNSIGNED,
	guestID					INT UNSIGNED,
	starRating				INT UNSIGNED NOT NULL,
	description				VARCHAR(350),
	CONSTRAINT FK_GUEST_ID_LISTING_REVIEW FOREIGN KEY (guestID) REFERENCES `GUEST`(id) ON DELETE CASCADE,
	CONSTRAINT FK_LISTING_ID_LISTING_REVIEW FOREIGN KEY (listingID) REFERENCES `LISTING`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `HOST REVIEW` (
	id						INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	hostID					INT UNSIGNED,
	guestID					INT UNSIGNED,
	starRating				INT UNSIGNED NOT NULL,
	description				VARCHAR(350),
	CONSTRAINT FK_HOST_ID_HOST_REVIEW FOREIGN KEY (hostID) REFERENCES `HOST`(id) ON DELETE CASCADE,
	CONSTRAINT FK_GUEST_ID_HOST_REVIEW FOREIGN KEY (guestID) REFERENCES `GUEST`(id) ON DELETE CASCADE
); ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `BOOKING` (
	id						INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	hostID					INT UNSIGNED,
	guestID					INT UNSIGNED,
	listingID				INT UNSIGNED,
	arriveDate				DATE NOT NULL,
	departDate				DATE NOT NULL,
	numAdults				INT UNSIGNED NOT NULL,
	numKids					INT UNSIGNED NOT NULL,
	paymentAmount			DECIMAL(7, 2),
	CONSTRAINT FK_HOST_ID_BOOKING FOREIGN KEY (hostID) REFERENCES `HOST`(id) ON DELETE CASCADE,
	CONSTRAINT FK_GUEST_ID_BOOKING FOREIGN KEY (guestID) REFERENCES `GUEST`(id) ON DELETE CASCADE,
	CONSTRAINT FK_LISTING_ID_BOOKING FOREIGN KEY (listingID) REFERENCES `LISTING`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
